	<script type="text/javascript" src="../js/jquery.min.js"></script>
	<script type="text/javascript" src="../js/popper.min.js"></script>
	<script type="text/javascript" src="../js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../js/xzoom.js"></script>
    <script type="text/javascript" src="../js/foundation.min.js"></script>
	<script type="text/javascript" src="../js/setup.js"></script>
	
</body>
</html>