		<!-- INICIA FOOTER -->

		<div class="container-fluid pie">
			<div class="container">
				<p class="display-4 text-center pt-5">Contáctanos</p>
				<p class="subtitulo text-center pb-4">Te ofrecemos, asesoría profesional.</p>

				<div class="row py-5">
					<div class="col-12 col-sm-12 col-md-6">
						<form action="../protected/php/verificar.php" method="post">
							<div class="row">
								<div class="form-group col-12 col-sm-6">
									<input type="text" class="form-control" name="txtNombre" placeholder="Nombre" required/>
								</div>
								<div class="form-group col-12 col-sm-6">
									<input type="email" class="form-control" name="txtCorreo" placeholder="Correo" required/>
								</div>
								<div class="form-group col-12">
									<textarea class="form-control" rows="5" name="txtMensaje" placeholder="Mensaje" required></textarea>
								</div>
								<div class="form-group col-12 col-sm-6 col-lg-4">
									<input type="submit" class="btn btn-outline-secondary btn-lg container-fluid" value="Enviar"/>
								</div>
								<div class="form-group col-12 col-sm-6 col-lg-4">
									<input type="reset" class="btn btn-outline-secondary btn-lg container-fluid" value="Limpiar"/>
								</div>
							</div>
						</form>
					</div>
					<div class="col-12 col-sm-12 col-md-6">
						<div class="row">
							<div class="col-12">
								<div class="row">
									<div class="col-12 col-sm-6">
										<div class="row">
											<div class="col-2 d-flex align-self-center justify-content-center">
												<i class="icono fab fa-facebook-square"></i>
											</div>
											<div class="col-10 d-flex align-self-center pl-0">
												<a href="https://www.facebook.com/kamilailuminacion/" class="text-muted redes">facebook.com/kamilailuminacion</a>
											</div>
										</div>
										<hr>
									</div>
									<div class="col-12 col-sm-6">
										<!-- <div class="row">
											<div class="col-2 d-flex align-self-center justify-content-center">
												<i class="icono fab fa-facebook-square"></i>
											</div>
											<div class="col-10 d-flex align-self-center pl-0">
												<a href="https://www.instagram.com/kamilailuminacion/" class="text-muted redes">instagram.com/kamilailuminacion</a>
											</div>
										</div>
										<hr> -->
									</div>

									<div class="col-12 col-sm-6">
										<!-- <div class="row">
											<div class="col-2 d-flex align-self-center justify-content-center">
												<i class="icono fab fa-facebook-square"></i>
											</div>
											<div class="col-10 d-flex align-self-center pl-0">
												<a href="https://www.facebook.com/kamilailuminacion/" class="text-muted redes">facebook.com/kamilailuminacion</a>
											</div>
										</div>
										<hr> -->
									</div>
								</div>
							</div>
						</div>
								
						
					</div>
				</div>
				<hr>

				<div class="row footerTexto">
					<div class="col-md-12 okfooter align-middle my-3">
								<p class="text-center">© kamila. Todos los derechos reservados. | Diseñado por: <a href="http://veltosystems.com/" class="text-muted">veltosystems.com</a></p>
					</div>
				</div>
		
			</div>
		</div>

	<!-- TERMINA FOOTER -->