		<!-- INICIA FOOTER -->

		<div class="container-fluid pie">
			<div class="container">
				<p class="display-4 text-center pt-5">Contáctanos</p>
				<p class="subtitulo text-center pb-4">Te ofrecemos, asesoría profesional.</p>

				<div class="row py-5">
					<div class="col-12 col-sm-6">
						<form action="" method="post">
							<div class="row">
								<div class="form-group col-12 col-sm-6">
									<input type="text" class="form-control" placeholder="Nombre"/>
								</div>
								<div class="form-group col-12 col-sm-6">
									<input type="text" class="form-control" placeholder="Correo"/>
								</div>
								<div class="form-group col-12">
									<textarea class="form-control" rows="5" placeholder="Mensaje"></textarea>
								</div>
								<div class="form-group col-12 col-sm-6 col-lg-4">
									<input type="submit" class="btn btn-outline-secondary btn-lg container-fluid" value="Enviar"/>
								</div>
								<div class="form-group col-12 col-sm-6 col-lg-4">
									<button type="button" class="btn btn-outline-secondary btn-lg container-fluid">Limpiar</button>
								</div>
							</div>
						</form>
					</div>
					<div class="col-12 col-sm-6">
						<div class="row">
							<div class="col-12">
								<div class="row">
									<div class="col-12 col-sm-6">
										<a href="#" class="text-muted">Link 1</a>
										<hr>
									</div>
									<div class="col-12 col-sm-6">
										<a href="#" class="text-muted">Link 2</a>
										<hr>
									</div>

									<div class="col-12 col-sm-6">
										<a href="#" class="text-muted">Link 3</a>
										<hr>
									</div>
								</div>
							</div>
						</div>
								
						
					</div>
				</div>
				<hr>

				<div class="row footerTexto">
					<div class="col-md-12 okfooter align-middle my-3">
								<p class="text-center">© kamila. Todos los derechos reservados. | Diseñado por: <a href="http://veltosystems.com/" class="text-muted">veltosystems.com</a></p>
					</div>
				</div>
		
			</div>
		</div>

	<!-- TERMINA FOOTER -->