<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/style.css">
	<link rel="stylesheet" href="../css/xzoom.css">
	<link rel="stylesheet" href="../css/animate.css">
	<script defer src="../js/all.js"></script>
	<title>Kamila Iluminación Residencial</title>
	<meta name="description" content="Fabricante de lámparas, candiles y plafones decorativos" />
</head>
<body>
