	<!-- INICIA MENU -->
	
	<div class="container-fluid cabecera">
		<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark">
		  <a class="navbar-brand" href="../inicio/kamila.aspx">KAMILA</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="../inicio/kamila.aspx">Inicio <span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="../quienes_somos/kamila.aspx">¿Quiénes somos?</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="../catalogo/kamila.aspx">Catalogo</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="../contacto/kamila.aspx">Contacto</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="https://webmail1.hostinger.mx">Correo</a>
		      </li>
		      <!-- <li class="nav-item">
		        <a class="nav-link disabled" href="#">Disabled</a>
		      </li> -->
		    </ul>
		    <form class="form-inline my-2 my-lg-0">
		      <input class="form-control mr-sm-2" type="text" placeholder="Buscar productos..." aria-label="Search">
		      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Buscar</button>
		    </form>
		  </div>
		</nav>
		</div>
	</div>
	
	<!-- TERMINA MENU -->